[package]
name = "rs-wappalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
reqwest = "0.12.5"
regex = "1.10.5"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"