[package]
name = "rs-wappalyzer"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["src/core", "src/cli", "src-tauri", "src-wasm"]
default-members = ["src/cli"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = true
